# Generated by Django 4.2.7 on 2023-12-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
