# Generated by Django 4.2.7 on 2023-12-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
