# Generated by Django 4.2.7 on 2023-12-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
