# Generated by Django 4.2.7 on 2023-12-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
